/**
 * A curated list of the English language's most frequent misspellings and
 * closed-compound errors, mapped straight to their correction. This is a
 * fast, high-confidence path that runs BEFORE the generic edit-distance
 * corrector: real-world typos ("recieve", "definately", "alot") are so
 * common and so consistent that a direct lookup beats a generic algorithm
 * for accuracy, exactly the way real spell checkers layer a "known typos"
 * list on top of their general algorithm.
 */
export const COMMON_MISSPELLINGS = {
  absense: "absence", acceptible: "acceptable", accidentaly: "accidentally",
  accomodate: "accommodate", accomodation: "accommodation", achievment: "achievement",
  acknowlege: "acknowledge", acknowledgement: "acknowledgment", acquaintence: "acquaintance",
  adress: "address", adressed: "addressed", advertisment: "advertisement",
  aggresive: "aggressive", allmost: "almost", alot: "a lot", althought: "although",
  amatuer: "amateur", apparant: "apparent", apparantly: "apparently",
  appearence: "appearance", arguement: "argument", arithmatic: "arithmetic",
  artic: "arctic", assasination: "assassination", athiest: "atheist",
  attendence: "attendance", auxilary: "auxiliary", awfull: "awful",
  basicly: "basically", becuase: "because", becomeing: "becoming",
  beggining: "beginning", begining: "beginning", beleive: "believe", belive: "believe",
  benifit: "benefit", benifits: "benefits", bizzare: "bizarre", buisness: "business",
  calender: "calendar", camoflage: "camouflage", catagory: "category",
  cemetary: "cemetery", changable: "changeable", cheif: "chief",
  collegue: "colleague", comming: "coming", commitee: "committee",
  comittment: "commitment", comparision: "comparison", competance: "competence",
  completly: "completely", concious: "conscious", conciousness: "consciousness",
  congradulate: "congratulate", consciencious: "conscientious", consistant: "consistent",
  continous: "continuous", contraversy: "controversy", curiousity: "curiosity",
  definately: "definitely", definate: "definite", dependant: "dependent",
  desparate: "desperate", develope: "develop", developement: "development",
  dilema: "dilemma", disapear: "disappear", disapoint: "disappoint",
  disapointed: "disappointed", disasterous: "disastrous", disipline: "discipline",
  ecstacy: "ecstasy", embarass: "embarrass", embarassed: "embarrassed",
  embarassment: "embarrassment", enviroment: "environment",
  equiptment: "equipment", erronous: "erroneous", exagerate: "exaggerate",
  excelent: "excellent", exhilerate: "exhilarate", existance: "existence",
  experiance: "experience", explaination: "explanation", familar: "familiar",
  finaly: "finally", flourescent: "fluorescent", foriegn: "foreign",
  fourty: "forty", freind: "friend", friendlyness: "friendliness", fullfil: "fulfill",
  fullfilment: "fulfillment", garantee: "guarantee", gaurd: "guard", gaurdian: "guardian",
  glamourous: "glamorous", goverment: "government", gratefull: "grateful",
  greatful: "grateful", harrass: "harass", harrassment: "harassment",
  humerous: "humorous", hygene: "hygiene", hipocrite: "hypocrite",
  ignorence: "ignorance", imaginery: "imaginary", imediately: "immediately",
  immediatly: "immediately", independant: "independent",
  inteligent: "intelligent", intergrate: "integrate", interupt: "interrupt",
  irrelevent: "irrelevant", irresistable: "irresistible", knowlege: "knowledge",
  labratory: "laboratory", liason: "liaison", libary: "library", lisence: "license",
  loneliness: "loneliness", maintainance: "maintenance", maintenence: "maintenance",
  managable: "manageable", maneuever: "maneuver", millenium: "millennium",
  milennium: "millennium", minature: "miniature", mischevious: "mischievous",
  mispell: "misspell", mispelled: "misspelled", momento: "memento",
  neccessary: "necessary", neccesary: "necessary", necesary: "necessary",
  neice: "niece", noticable: "noticeable", nowdays: "nowadays",
  occassion: "occasion", occassionally: "occasionally", occurance: "occurrence",
  occured: "occurred", ommision: "omission", oppurtunity: "opportunity",
  orignal: "original", outragous: "outrageous", paralell: "parallel",
  parliment: "parliament", particurly: "particularly", pasttime: "pastime",
  peculier: "peculiar", percieve: "perceive", perseverence: "perseverance",
  performence: "performance", personnell: "personnel", persaude: "persuade",
  pharoah: "pharaoh", phenomenom: "phenomenon", playright: "playwright",
  posession: "possession", potatoe: "potato", preceed: "precede",
  prefered: "preferred", prefering: "preferring", presance: "presence",
  priviledge: "privilege", probaly: "probably", proffesional: "professional",
  promiss: "promise", pronounciation: "pronunciation", propoganda: "propaganda",
  publically: "publicly", quarentine: "quarantine", questionaire: "questionnaire",
  readible: "readable", realy: "really", recieve: "receive", recieved: "received",
  recieving: "receiving", recomend: "recommend", recomended: "recommended",
  refered: "referred", referal: "referral", relevent: "relevant",
  religous: "religious", remeber: "remember", repitition: "repetition",
  reponsible: "responsible", resistence: "resistance", restaraunt: "restaurant",
  rythm: "rhythm", sacrafice: "sacrifice", saftey: "safety", secratary: "secretary",
  seperate: "separate", seperated: "separated", seperately: "separately",
  seige: "siege", similer: "similar", sincerly: "sincerely", speach: "speech",
  succsess: "success", succesful: "successful", succesfully: "successfully",
  suprise: "surprise", suprised: "surprised", supress: "suppress",
  temperture: "temperature", tendancy: "tendency", thier: "their",
  tommorow: "tomorrow", tommorrow: "tomorrow", tomatos: "tomatoes",
  tounge: "tongue", truely: "truly", twelth: "twelfth", tyrany: "tyranny",
  unfortunatly: "unfortunately", unforseen: "unforeseen", unnecesary: "unnecessary",
  untill: "until", vaccum: "vacuum", vegetible: "vegetable", wich: "which",
  wierd: "weird", wellcome: "welcome", writting: "writing", yeild: "yield",

  // closed-compound errors (two words wrongly written as one)
  infact: "in fact", aswell: "as well", atleast: "at least", incase: "in case",
  inspite: "in spite", everytime: "every time", eachother: "each other",
  noone: "no one", ofcourse: "of course", inorder: "in order",
  thankyou: "thank you", cannotbe: "cannot be",
};
